python jemdoc.py MENU
python jemdoc.py -c mysite.conf BjutThsis.jemdoc
python jemdoc.py -c mysite.conf DMS.jemdoc
python jemdoc.py -c mysite.conf ESM.jemdoc
python jemdoc.py -c mysite.conf index.jemdoc
python jemdoc.py -c mysite.conf IOTS.jemdoc
python jemdoc.py -c mysite.conf Keywords.jemdoc
python jemdoc.py -c mysite.conf Paper.jemdoc
python jemdoc.py -c mysite.conf Project.jemdoc
python jemdoc.py -c mysite.conf Service.jemdoc
python jemdoc.py -c mysite.conf SG.jemdoc
python jemdoc.py -c mysite.conf Student.jemdoc
python jemdoc.py -c mysite.conf Tawards.jemdoc
python jemdoc.py -c mysite.conf TBData.jemdoc
python jemdoc.py -c mysite.conf TREC.jemdoc
python jemdoc.py -c mysite.conf People.jemdoc
python jemdoc.py -c mysite.conf TongLi.jemdoc
python jemdoc.py -c mysite.conf HaiyangYu.jemdoc
python jemdoc.py -c mysite.conf IIS.jemdoc